# Windows 静态编译配置（已有的）
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# Linux 静态编译配置（新增的）
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
